- name: disable firewalld
  become: yes
  service: name=firewalld state=stopped enabled=no
  ignore_errors: True  #when firewalld is stopped
  tags: kafka

- name: install tools
  become: yes
  yum: name="@Development tools" state=present
  tags: kafka

- name: create group
  become: yes
  group:
    name: kafka
    state: present
  tags: kafka

- name: create user
  become: yes
  user:
    name: kafka
    group: kafka
  tags: kafka

- name: Setting internal variable
  become: yes
  set_fact:
    kafka_name: kafka_{{ kafka.scala_version }}-{{ kafka.version }}
  tags: kafka

- name: Setting internal variable
  become: yes
  set_fact:
    kafka_dir: "{{ kafka.install_dir }}/{{ kafka_name }}"
  tags: kafka

- name: check if tar has been downloaded
  become: yes
  command: test -f /tmp/{{ kafka_name }}.tgz
  register: kafka_tar_downloaded
  failed_when: kafka_tar_downloaded.rc not in [0, 1]
  changed_when: False
  tags: kafka

- name: Ensure Kafka tar is downloaded
  become: yes
  get_url:
    url: "{{ kafka.mirror }}/kafka/{{ kafka.version }}/{{ kafka_name }}.tgz"
    dest: /tmp
  tags: kafka
  when: kafka_tar_downloaded.rc == 1

- name: Ensure tar is extracted
  become: yes
  command: tar xzf /tmp/{{ kafka_name }}.tgz chdir="{{ kafka.install_dir }}"
  tags: kafka

# Config and start Kafka
- name: Ensures data dir {{ kafka.data_dir }} exists
  become: yes
  file:
    path: "{{ kafka.data_dir }}"
    state: directory
    owner: kafka
    group: kafka
  tags: kafka

- name: Copy real config {{ zk_client_port }}
  become: yes
  template:
    src: kafka-properties.j2
    dest: "{{ kafka_dir }}/config/real-server.properties"
  notify: restart kafka
  tags: kafka

- name: systemd start script
  become: yes
  template:
    src: kafka-systemd.j2
    dest: /etc/systemd/system/kafka.service
    owner: root
    group: root
    mode: 644
  notify: start kafka
  tags: kafka
